# ---
# jupyter:
#   jupytext:
#     formats: ipynb,py:percent
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: '1.3'
#       jupytext_version: 1.13.7
#   kernelspec:
#     display_name: Python [default]
#     language: python
#     name: python2
# ---

# %%
import pandas as pd
import numpy as np

import prms_lib as prms
reload(prms)

# %% [markdown]
# #### Process the tstorm_mo files generated by the GDP and create a single-parameter parameter file for each region

# %%
regions = ['01', '02', '03', '04', '05',
           '06', '07', '08', '09', '10U',
           '10L', '11', '12', '13', '14',
           '15', '16', '17', '18']
# region = "10U"

for region in regions:
    print 'Region:', region
    gdp_data_dir = '/media/scratch/PRMS/datasets/tstorm_mo'
    gdp_data_file = '%s/TSTORM_MO_TSTORM_Monthly_r%s_byHRU_2010-01-01_2010-12-01.csv' % (gdp_data_dir, region)

    prms_region_dir = '/media/scratch/PRMS/regions/paramDb/tmp' #% region
    prms_region_file = '%s/r%s_params' % (prms_region_dir, region)
    prms_region_outfile = '%s/input_params/r%s_params.tstorm_mo' % (gdp_data_dir, region)

    # Read the GDP file
    df_gdp = prms.read_gdp(gdp_data_file, 255.)

    # Transpose from nmonths x nhru to nhru x nmonths and return ndarray
#     bb = df_gdp.T.values
    bb = df_gdp.values.flatten()

    # Open input parameter file
    params = prms.parameters(prms_region_file)

    # Replace the tstorm_mo values with the new ones
    params.replace_values('tstorm_mo', bb)

    # Write out new input parameter file
    params.write_select_param_file(prms_region_outfile, ['tstorm_mo'])

# %%
